version: 0.2
            
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install --upgrade awscli
  pre_build:
    commands:
      - pip3 install -r cloudformation/requirements.txt
  build:
    commands:
      - cd cloudformation && invoke build && cd ..
  post_build:
    commands:
      - echo 'Finished building templates'
      - ls -al cloudformation/output
artifacts:
  files:
    - cloudformation/output/*.json